/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package rentalbarang;
//Library
import java.sql.Connection; //Mengkoneksikan java dengan SQL.
import java.sql.ResultSet; //resultset adalah pengontrol letak kursor terhadap suatu baris didalam database.
import java.sql.SQLException; // Untuk menangani kesalahan-kesalahan yang mungkin terjadi saat pengolahan database
import java.sql.Statement; //Untuk mengantarkan syntax SQL yang ditulis di java ke dalam database
import javax.swing.JOptionPane; //Untuk menyediakan jendela dialog.
import java.awt.Dimension; //Untuk mendapatkan dimensi lebar atau tinggi suatu komponen dalam int atau double.
import java.awt.Toolkit; //Salah satu fungsinya Untuk mendapatkan ukuran jendela.
/**
 @author Kelompok 8
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     * 
     */
    public Login() {
        initComponents();
        //Berfungsi agar window berada di tengah dengan menggunakan library Dimension 
        // dan toolkit agar bisa mendapatkan ukuran layar.
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width / 2 - this.getSize().width / 2; //Mendaatkan Lebar layar.
        int y = layar.height / 2 - this.getSize().height / 2; //Mendapatkan tinggi layar.
        this.setLocation(x,y); //Meletakan lokasi jendela tepat di tengah layar.
    }
    
     
    public void kirim(String NPM){
        //mendapatkan  nilai NPM dari Register
        npmtype.setText(NPM); // meletakan nilai NPM diatas Text Field
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 
    //Pembuatan Component-component desain dari template swing java
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passtype = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        regis = new javax.swing.JButton();
        npmtype = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Login");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("NPM");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Password");

        passtype.setBackground(new java.awt.Color(255, 255, 255));

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setForeground(new java.awt.Color(0, 0, 0));
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        regis.setBackground(new java.awt.Color(255, 255, 255));
        regis.setForeground(new java.awt.Color(0, 0, 0));
        regis.setText("Register");
        regis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisActionPerformed(evt);
            }
        });

        npmtype.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 149, Short.MAX_VALUE)
                .addComponent(regis)
                .addGap(28, 28, 28)
                .addComponent(login)
                .addGap(78, 78, 78))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(npmtype)
                            .addComponent(passtype, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(npmtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login)
                    .addComponent(regis))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // Fungsi Button Login
        try {
            // Mengkoneksikan fungsi dengan SQL
            Connection c =  koneksi.getkoneksi();
            Statement s = c.createStatement();
         
            // Mengubah nilai text menjadi string.
            String NPM = npmtype.getText().toString().trim();
            
            // Membuat string berisikan syntax SQL.
            String sql = "SELECT * FROM tb_peminjam WHERE NPM='" + npmtype.getText()
                    +"' and Password='"+ passtype.getText() + "'";
            
            //resultset adalah pengontrol letak kursor terhadap suatu baris didalam database, 
            //sehingga apa yg kita pilih / select  dari java, akan sesuai dengan data baris yg ada pada database.
            ResultSet r = s.executeQuery(sql);
            
            
            if (r.next()) //Mengakses setiap baris pada tabel SQL
            {
                JOptionPane.showMessageDialog(null,"Login Succesfully"); //Menggunakan Library JOption untuk menyediakan jendela dialog
                this.dispose(); //Mendispose (menghancurkan) window Login
                frmbarang a = new frmbarang(); //Membuat jendela dari class frmbarang.
                a.kirim(NPM); //mengirim nilai NPM ke fungsi kirim yang ada di objek frmbarang.
                a.setVisible(true); //Untuk menampilkan frame frmbarang yang sdh di panggil namun msh hanya berupa memori.
            }
            else{
                JOptionPane.showMessageDialog(null, "wrong NPM or Password");
                passtype.requestFocus(); //requestFocus merupakan method agar Listener mendeteksi apapun inputan kita
            }
        } catch (SQLException e) {
            System.out.println(" login Error");  //memberi string login error bila pengolahan SQL gagal.
        }
    }//GEN-LAST:event_loginActionPerformed

    private void regisActionPerformed(java.awt.event.ActionEvent evt) 
    {//GEN-FIRST:event_regisActionPerformed
     
        // Fungsi Button Registrasi
        this.dispose(); //Mendispose window Login
        Register a = new Register(); //Membuat jendela dari class Regristrasti.
        a.setVisible(true); //Menampilkan jendela Regristrasi.
        
    }//GEN-LAST:event_regisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true); //Menampilkan fungsi Login.
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JTextField npmtype;
    private javax.swing.JTextField passtype;
    private javax.swing.JButton regis;
    // End of variables declaration//GEN-END:variables
}
